language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
before_script:
  - npm install -g grunt-cli
after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
dist: trusty
sudo: false
cache: yarn
